### ISSUE TITLE
[Tracking] [AWS] AWS Web Server Setup

### ISSUE THREAD

**Issue by derekdhuynh** [ClaimsCompass/ClaimsCompass#9]
We have happily conceded to Mr. Bezo's greatness and settled on hosting our full stack on EC2.  Unfortunately, there is some non-trivial set up steps we'll need to get done before our hosting situation is fully resolved:

- [X] [[AWS] Initial EC2 Web App Demo](https://github.com/ClaimsCompass/ClaimsCompass/issues/8)
- [ ] [[AWS] EC2 Access For Team](https://github.com/ClaimsCompass/ClaimsCompass/issues/2)
- [ ] [[AWS] PostGres to AWS database migrate](https://github.com/ClaimsCompass/ClaimsCompass/issues/6)
- [ ] [[AWS] Set up Nginx Server For EC2 Instance](https://github.com/ClaimsCompass/ClaimsCompass/issues/7)

**Comment by derekdhuynh** [comment]
Note that full access to AWS console might be more involved than needed. Need to check in if SSH access is ok and I will just turn the instance on when needed.
